[features]
seeds = false
skip-lint = false
[programs.localnet]
helloworld = "EyPYzW5RV3Fn643HKaA52boiUysPbwKbXfPZpBRUsStu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/hangyeonghyeon/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
